import type { Metadata } from 'next';
import './globals.css';
import SideBar from '@/components/SideBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <main className='flex'>
          <SideBar />
          <div className='bg-gray-100 w-full'>{children}</div>
        </main>
      </body>
    </html>
  );
}
