import type { Metadata } from 'next';
import './globals.css';
import SideBar from '@/components/SideBar';
import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';
import Web3ModalProvider from '@/components/Web3ModalProvider';
import { config } from '@/config';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'));
  return (
    <html lang='en'>
      <body>
        <main className='flex'>
          <Web3ModalProvider initialState={initialState}>
            <Toaster />
            <SideBar />
            <div className='bg-gray-100 w-full'>{children}</div>
          </Web3ModalProvider>
        </main>
      </body>
    </html>
  );
}
